base_url = "https://club-de-algoritmia-acatlan-guapa.github.io/"

theme = "even"
compile_sass = true
title = "GUAPA"
generate_feed = true

taxonomies = [
    {name = "categories", rss = false},
    {name = "tags", rss = false},
]

minify_html = true

[extra]
author = "Bruno A. Muciño @mucinoab"

even_menu = [
    {url = "$BASE_URL/nosotros", name = "Acerca de Nosotros "},
    {url = "$BASE_URL/contacto", name = "Contacto "},
]

even_title = "GUAPA"

katex_enable = false
katex_auto_render = false

favicon = "/static/favicon.ico"


